source 'https://rubygems.org'
gem 'sinatra', '~> 1.4', '>= 1.4.7'
gem 'sinatra-contrib', '~> 1.4', '>= 1.4.7'
gem 'httparty', '~> 0.14.0'
gem 'nokogiri', '~> 1.6', '>= 1.6.8'
gem 'byebug'
gem 'memcachier'
gem 'dalli'
